### ISSUE TITLE
Flex2's image importing remembers images too well

### ISSUE THREAD

**Issue by VAdaPEGA** [kirjavascript/Flex2#42]
When trying to **import over a sprite** or **import a spritesheet**, it will remember that file the last time you used it to import.
Say you have it open in a image editor and you change one or two pixels, perhaps a whole tile worth of changes while Flex2 is still open **after having imported that same file before making changes**, it will use the **old incorrect version of the file it had loaded beforehand** and not reload the file, having to resort to either renaming the file or closing and re-opening Flex2 to get around it, which is annoying.

Hopefully the explanation is sufficient, It's 11PM and I'm kinda tired so I apologize for any misinterpretations!

**Comment by kirjavascript** [comment]
That that makes sense, thanks for finding the bug!

I'll make sure it's fixed in the next version

**Comment by kirjavascript** [comment]
does this still happen? I cant seem to replicate it

**Comment by VAdaPEGA** [comment]
Still happens to an extent, just tested it, here's a video of it. (image isn't indexed)

https://user-images.githubusercontent.com/50675500/216818665-1adb03f5-2b4a-4217-bab4-da470529b21a.mp4

**Comment by kirjavascript** [comment]
will be in next release
